name: Build
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  n7gg:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install thx
        run: |
          pip install -U pip
          pip install -U thx
      - name: Test
        run: thx --live test
      - name: Lint
        run: thx --live lint
